name: Build

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup prerequisites
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install pkg-config libudev-dev libusb-1.0-0-dev

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Build
        run: |
          npm install
          npm run pack
          npm run dist:draft

      - name: Check files
        run: ls -alR --ignore=\.git --ignore=node_modules

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Blink1Control2-linux
          path: |
            dist/Blink1Control2*deb
            dist/Blink1Control2*tar.gz
            dist/Blink1Control2*AppImage

      # - name: npm test
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # run: |
        #   npm run package
        #   npm run lint
        #   npm exec tsc
        #   npm test
