# Build macOS, optionally sign

name: windows

env:
  WINDOWS_CERTIFICATE_P12: ${{ secrets.WINDOWS_CERTIFICATE_P12 }}
  CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PWD }}
  CSC_LINK: "C:\win-certificate.p12"
  #GH_TOKEN: ${{ secrets.GH_TOKEN }}
  # see https://shipshape.io/blog/signing-electron-apps-with-github-actions/

# Controls when the action will run. Triggers the workflow
# on push or pull request events but only for the main branch
on:
  push:
  pull_request:
  release:
    types: [created]

# A workflow run is made of jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks executed as part of the job
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup prerequisites
        run: echo "no prereqs to set up"

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Codesign setup for Windows
        #if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/')
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "C:\win-certificate.p12"
          encodedString: ${{ secrets.WINDOWS_CERTIFICATE_P12 }}

      - name: Build
        run: |
          npm install
          npm run pack
          npm run dist:draft

      - name: Publish
        continue-on-error: true
        if: github.event.release.action == 'created'
        run: |
          npm run dist

      #- name: Check files
      #  run: ls -alR --ignore=\.git --ignore=node_modules

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Blink1Control2-${{ runner.os }}
          path: |
            dist/Blink1Control2*zip
            dist/Blink1Control2*dmg
            dist/Blink1Control2*deb
            dist/Blink1Control2*tar.gz
            dist/Blink1Control2*AppImage
            dist/Blink1Control2*exe
